### ISSUE TITLE
testProject.aep unreadable

### ISSUE THREAD

**Issue by evanbbb** [Jam3/ae-to-json#10]
Opening testProject.aep with AE CC v13.5.1 on a windows7 machine and getting a "unable to import file" error. "Bad format or not readable"

CC is up-to-date

**Comment by mikkoh** [comment]
@evanbbb so the AE file opens but it fails importing assets? There is one asset that gets loaded which is an image. I was worried that AE doesn't use relative paths to bring in that asset but I'm not 100% sure thats the case from the above error.

**Comment by mikkoh** [comment]
@evanbbb I noticed AE is now able to export XML versions of projects. (don't know how new this is)

I've exported a file called `testProjectXML.aepx`. Can you let me know if that file works? I went in and manually updated the path to the file to be relative.

**Comment by evanbbb** [comment]
AE doesn't open the file and I don't think it has to do with the asset.

The aepx seems to load fine but with the 'Placeholder' missing. To make sure everything stays wrapped nicely, you can do a Dependencies->Collect Files

**Comment by mikkoh** [comment]
Ah yes Collect Files. It's been awhile since I've used AE. Let me do that. Although it's wierd cause I went in and manually modified pathing to be relative in the aepx file. I will delete the `testProject.aep` file and replace with the `aepx` file. Appreciate you looking at this.

**Comment by mikkoh** [comment]
I was reading some other people talking about aepx files. And they were saying that pathing is a bit more complex in AE:

```
<fileReference ascendcount_base="1" ascendcount_target="2" fullpath="/Users/mikkohaapoja/Documents/Modules/ae-to-json/test/ae/(Footage)/jam3Logo.png" platform="MacPOSIX" server_name="" server_volume_name="Macintosh HD" target_is_folder="0"/>
```

Thats the path to the footage. They were suggesting that `ascendcount_base` and `ascendcount_target` actually point to a section of the aepx file where there is binary data that encodes the "true" path to the footage.

So... I've collected footage and now it sits in the `test/ae` folder. I've also added npm scripts to simply say:

`$ npm test`
or 
`$ npm start`

Which will open AE run tests. The difference being `start` will watch `.js` files to make for a somewhat nicer dev experience.

**Comment by mikkoh** [comment]
@evanbbb just wondering if you had a chance to test the new aepx file?

**Comment by evanbbb** [comment]
opens fine, the png does not parse. Tried a couple programs on windows (paint, chrome, photoshop) but nothing will open.

**Comment by mikkoh** [comment]
@evanbbb do you have git lfs installed?

**Comment by evanbbb** [comment]
I do now... :+1: 
And can get the png (with some fiddling) which works fine in AE.

**Comment by mikkoh** [comment]
Ok cool... Thanks so much for testing this. :+1:
